services:
  grayscale_service:
    build: ./grayscale
    container_name: grayscale_service
    ports:
      - "5001:5001"
    networks:
      - image_processing_net

  gaussian_blur_service:
    build: ./gaussian_blur
    container_name: gaussian_blur_service
    ports:
      - "5002:5002"
    networks:
      - image_processing_net

  nginx:
    image: nginx:latest
    container_name: nginx_load_balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - image_processing_net
    depends_on:
      - grayscale_service
      - gaussian_blur_service

networks:
  image_processing_net:
    driver: bridge
 
